wandb_version: 1

__cached__setup_devices:
  desc: null
  value:
  - cuda
  - 1
_wandb:
  desc: null
  value:
    cli_version: 0.8.35
    code_path: code/FullCode/run_language_modeling.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.5
adam_epsilon:
  desc: null
  value: 1.0e-08
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
do_train:
  desc: null
  value: true
evaluate_during_training:
  desc: null
  value: true
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
gradient_accumulation_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
local_rank:
  desc: null
  value: -1
logging_dir:
  desc: null
  value: null
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 500
max_grad_norm:
  desc: null
  value: 1.0
max_steps:
  desc: null
  value: -1
no_cuda:
  desc: null
  value: false
num_train_epochs:
  desc: null
  value: 5.0
output_dir:
  desc: null
  value: ./model/full_code
overwrite_output_dir:
  desc: null
  value: false
per_gpu_eval_batch_size:
  desc: null
  value: 8
per_gpu_train_batch_size:
  desc: null
  value: 1
save_steps:
  desc: null
  value: 2000
save_total_limit:
  desc: null
  value: 2
seed:
  desc: null
  value: 42
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
